# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cawaR2 <- function(x, y) {
    .Call('_CAWaR_cawaR2', PACKAGE = 'CAWaR', x, y)
}

